version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing dependencies...
      # Use --prefix to force npm to run inside the frontend folder
      - npm install --prefix frontend
  build:
    commands:
      - echo Build started on `date`
      # Use --prefix to force npm to run the build script inside the frontend folder
      - npm run build --prefix frontend

artifacts:
  files:
    - 'frontend/dist/**/*'