version: 0.2

env:
  variables:
    TF_DIR: "terraform"
    TF_VERSION: "1.5.7"

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - yum update -y
      - yum install -y unzip curl jq
      - curl -sSL "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip" -o terraform.zip
      - unzip -o terraform.zip -d /usr/local/bin/
      - chmod +x /usr/local/bin/terraform
      - terraform version

  pre_build:
    commands:
      - echo "=== Pre-build Validation ==="
      - cd $TF_DIR
      - terraform init -input=false
      - terraform validate
      - cd ..

  build:
    commands:
      - echo "=== Running Terraform Plan ==="
      - cd $TF_DIR
      - export TF_VAR_environment=$ENVIRONMENT
      - terraform plan -input=false -out=tfplan
      
      - echo "=== Applying Infrastructure changes ==="
      - terraform apply -auto-approve -input=false tfplan
      
      - echo "=== Capturing Terraform Outputs ==="
      - terraform output -json > ../tf_outputs.json
      - cd ..
      - cat tf_outputs.json

artifacts:
  files:
    - tf_outputs.json
  discard-paths: yes